---
- name: Apply the geerlingguy.jenkins role to all ci_servers
  hosts: ci_servers
  roles:
    - geerlingguy.git
    - geerlingguy.jenkins
    - geerlingguy.nginx
    - geerlingguy.firewall
  vars:
    jenkins_version: 2.53
    firewall_allowed_tcp_ports:
      - "22"
      - "80"
    nginx_vhosts:
      - listen: "80"
        server_name: "jenkins.local.app"
        extra_parameters: |
          location / {
 
              proxy_set_header        Host $host:$server_port;
              proxy_set_header        X-Real-IP $remote_addr;
              proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
              proxy_set_header        X-Forwarded-Proto $scheme;
          
              # Fix the "It appears that your reverse proxy set up is broken" error.
              proxy_pass          http://127.0.0.1:8080;
              proxy_read_timeout  90;
          }
